### ISSUE TITLE
1.9 Crash when trying to sleep

### ISSUE THREAD

**Issue by Ozzymud** [shadowfacts/SleepingBag#1]
http://pastebin.com/yJQU5H7t

Nothing much to add, was stading on polished andesite and the sun had just set if that matters?

**Comment by Ozzymud** [comment]
And crash trying to reload the world... http://pastebin.com/ugLhsDNr

**Comment by shadowfacts** [comment]
JWIN is broken. It incorrectly assumes that there will be a bed block when the player is sleeping. 

See ssblur/Just-What-I-Needed-Mod#10.

Your best bet for fixing the world is to use a backup or temporarily remove JWIN.
