### ISSUE TITLE
dupe bug

### ISSUE THREAD

**Issue by vertex101** [shadowfacts/SleepingBag#2]
if u put a sleeping bag in your off hand and you go to right click it dupes the bag over and over

here is a video i recording showing you the dupe bug

http://youtu.be/2c5LK8XxF68?hd=1

**Comment by shadowfacts** [comment]
Fixed for Sleeping Bag 1.2.1 (currently pending approval on CurseForge).

**Comment by vertex101** [comment]
the update was for 1.9.4 i am using the 1.9 version of the mod

**Comment by shadowfacts** [comment]
Sorry, 1.9 isn't being maintained anymore. Almost all 1.9 mods have been updated to 1.9, you should be able to update.
