### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by vertex101** [shadowfacts/SleepingBag#3]
i am getting a crash when trying to make a server for my modpack and it is coming from the lib file and figured i would post and see what you can find out it is line 22 - 26

[crash-2016-06-18_00.18.47-server.txt](https://github.com/shadowfacts/SleepingBag/files/321588/crash-2016-06-18_00.18.47-server.txt)

**Comment by shadowfacts** [comment]
See the ShadowMC issue linked above.

**Comment by shadowfacts** [comment]
Fixed in ShadowMC 3.3.9 which is currently pending approval on CurseForge.
