### ISSUE TITLE
"Stuck" sleeping

### ISSUE THREAD

**Issue by instinxx** [shadowfacts/SleepingBag#4]
MC 1.10.2
Forge 2089

Players get stuck after sleeping. Cant leave bed, cannot teleport them out. Fix seems to be game restart. No error msg shown.

**Comment by shadowfacts** [comment]
Are there any other mods in your instance that affect sleep mechanics?

**Comment by Catphalem** [comment]
This happened to me few times too.
Looked like whenever I try to sleep at the same time when it changes to daytime, I get stuck in the bed.
Also when other player comes online when I'm still in the bed.
But it happened before I added this mod on our server.
So my experience is not really gonna be a helpful info...

**Comment by shadowfacts** [comment]
@Catphalem Since this was happening before you added my mod, I doubt it's an issue with SleepingBag.

**Comment by shadowfacts** [comment]
Closing b/c unable to reproduce and no response from author.
