### ISSUE TITLE
Couldn't write packet net.shadowfacts.shadowmc.network.PacketSpamlessMessage

### ISSUE THREAD

**Issue by SmallSansSerif** [shadowfacts/SleepingBag#5]
http://pastebin.com/q590Bk9a

Error in log using latest build:

SleepingBag-1.10.2-1.3.0.jar
ShadowMC-1.10.2-3.4.6.jar

**Comment by shadowfacts** [comment]
Fixed in ShadowMC 3.4.7 (on CurseForge [here](https://minecraft.curseforge.com/projects/shadowmc/files/2333131), currently pending approval).

**Comment by SmallSansSerif** [comment]
Thanks! Will give it a try 👍
